### ISSUE TITLE
how to learn python?

### ISSUE THREAD

**Issue by yanyongqi911** [yanyongqi911/yan#1]
how to use the github to learn code?like python.

**Comment by 07ATUL** [comment]
Hi @yanyongqi911 you can first try to cover up the basics of the language using a book or some vedio lectures and then try to practise questions from GeeksforGeeks, after you feel comfortable you can search for python in github search where you will get data structures and algorithms implemented in Python , you can search github for free ebooks as well. Now you are ready to take on issues in Python.
Happy Coding.

**Comment by yanyongqi911** [comment]
thanks @07ATUL , I am trying.
